version: "3"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    network_mode: bridge
    volumes:
      - ./logs:/opt/teamcity/logs
      - ./datadir:/data/teamcity_server/datadir
    ports:
      - 9898:8111

  teamcity-agent:
    image: jetbrains/teamcity-agent
    network_mode: bridge
    volumes:
      - ./teamcity-agent-conf:/data/teamcity_agent conf
    depends_on:
      - teamcity-server
    links:
      - teamcity-server
    environment:
      SERVER_URL: "http://172.17.0.1:9898"
